apps/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import AuthView, CustomLoginView

app_name = "auth"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "register/",
        AuthView.as_view(template_name="auth_register_basic.html"),
        name="register",
    ),
    path(
        "forgot_password/",
        AuthView.as_view(template_name="auth_forgot_password_basic.html"),
        name="forgot-password",
    ),
]

apps/passports/urls.py
from django.urls import path

from .views import PassportListView, public_passport

app_name = 'passports'
urlpatterns = [
    path('list/', PassportListView.as_view(), name='list'),
    path("p/<slug:number>/", public_passport, name="public"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config import settings
from apps.passports.views import RegistryDashboardView
from web_project.views import SystemView
from django.views.generic import RedirectView

admin.site.site_header = 'Реестр паспортов'
admin.site.site_title = 'Реестр паспортов'

urlpatterns = [
    path("admin/", admin.site.urls),

    path("auth/", include("apps.authentication.urls", namespace="auth")),

    path("dashboard/", RegistryDashboardView.as_view(), name="dashboard"),
    path('', RedirectView.as_view(pattern_name='dashboard', permanent=False)),

    path("", include("apps.passports.urls", namespace="passports")),
    path("", include("apps.pages.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = SystemView.as_view(template_name="pages_misc_error.html", status=404)
handler400 = SystemView.as_view(template_name="pages_misc_error.html", status=400)
handler500 = SystemView.as_view(template_name="pages_misc_error.html", status=500)

templates/layout/partials/menu/vertical/vertical_menu.html
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <!-- ! Hide app brand if navbar-full -->
  {% if not navbar_full %}
  <div class="app-brand demo">
    <a href="{% url 'dashboard' %}" class="app-brand-link">
      <span class="app-brand-logo demo">
        {% include 'partials/logo.html' with withbg="#696cff" %}
      </span>
      <span class="demo menu-text fw-bold ms-2">{% get_theme_variables 'template_name' %}</span>
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm d-flex align-items-center justify-content-center"></i>
    </a>
  </div>
  {% endif %}


  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1">

    <li class="menu-item {% if '/dashboard/' in request.path %}active{% endif %}">
      <a href="{% url 'dashboard' %}" class="menu-link">
        <i class="menu-icon tf-icons bx bx-analyse"></i>
        <div class="text-truncate" data-i18n="Analytics">Аналитика</div>
      </a>
    </li>
    <li class="menu-item {% if '/list/' in request.path %}active{% endif %}">
      <a href="{% url 'passports:list' %}" class="menu-link">
        <i class="menu-icon tf-icons bx bx-collection"></i>
        <div class="text-truncate">Список Паспортов</div>
      </a>
    </li>

<!--    &lt;!&ndash; Account &ndash;&gt;-->
<!--    <li class="menu-item {% if '/account_settings/' in request.path %}active open{% endif %}">-->
<!--      <a href="javascript:void(0);" class="menu-link menu-toggle">-->
<!--        <i class="menu-icon tf-icons bx bx-dock-top"></i>-->
<!--        <div class="text-truncate" data-i18n="Account Settings">Account Settings</div>-->
<!--      </a>-->
<!--      <ul class="menu-sub">-->
<!--        <li class="menu-item {% if '/account/' in request.path %}active{% endif %}">-->
<!--          <a href="{% url 'pages-account-settings-account' %}" class="menu-link">-->
<!--            <div class="text-truncate" data-i18n="Account">Account</div>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="menu-item {% if '/notifications/' in request.path %}active{% endif %}">-->
<!--          <a href="{% url 'pages-account-settings-notifications' %}" class="menu-link">-->
<!--            <div class="text-truncate" data-i18n="Notifications">Notifications</div>-->
<!--          </a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </li>-->
<!--    &lt;!&ndash; Auth &ndash;&gt;-->
<!--    <li class="menu-item {% if '/auth/' in request.path %}active open{% endif %}">-->
<!--      <a href="javascript:void(0);" class="menu-link menu-toggle">-->
<!--        <i class="menu-icon tf-icons bx bx-lock-open-alt"></i>-->
<!--        <div class="text-truncate" data-i18n="Authentications">Authentications</div>-->
<!--      </a>-->
<!--      <ul class="menu-sub">-->
<!--        <li class="menu-item {% if '/login/' in request.path %}active{% endif %}">-->
<!--          <a href="{% url 'auth:login' %}" class="menu-link" target="_blank">-->
<!--            <div class="text-truncate" data-i18n="Login">Login</div>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="menu-item {% if '/register/' in request.path %}active{% endif %}">-->
<!--          <a href="{% url 'auth:register' %}" class="menu-link" target="_blank">-->
<!--            <div class="text-truncate" data-i18n="Register">Register</div>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="menu-item {% if '/forgot_password/' in request.path %}active{% endif %}">-->
<!--          <a href="{% url 'auth:forgot-password' %}" class="menu-link" target="_blank">-->
<!--            <div class="text-truncate" data-i18n="Frogot Password">Frogot Password</div>-->
<!--          </a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </li>-->

<!--    <li class="menu-header small text-uppercase">-->
<!--      <span class="menu-header-text">Components</span>-->
<!--    </li>-->


  </ul>


</aside>